language: shell

git:
  depth: 3

install:
- source ci/install-test-deps.${TRAVIS_OS_NAME}.sh

script:
- mkdir build && cd build
- cmake ${TARGET_PLATFORM:+-A ${TARGET_PLATFORM}} ..
- cmake --build . --config RelWithDebInfo
- ctest --output-on-failure -C RelWithDebInfo

matrix:
  include:
  - os: osx
  - os: linux
  - os: windows
    name: Win32
    env: TARGET_PLATFORM=Win32
  - os: windows
    name: Win64
    env: TARGET_PLATFORM=x64
