language: shell

git:
  depth: 3

script:
- env
- mkdir build && cd build
- cmake ..
- cmake --build .
- ctest --output-on-failure

matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
    install:
    # Required for safe-download script
    - choco install openssl.light
