language: shell

git:
  depth: 3

script:
- mkdir build && cd build
- cmake ..
- cmake --build . --config RelWithDebInfo
- ctest --output-on-failure -C RelWithDebInfo

matrix:
  include:
  - os: linux
    install:
    - sudo apt-get install libsndfile1-dev portaudio19-dev
  - os: osx
    install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install libsndfile portaudio
  - os: windows
    install:
    # Required for safe-download script
    - choco install openssl.light
    - source ci/install-test-deps.windows.sh
