if(DEFINED _GetWindowsProgramFilesDirIncluded)
    return()
endif()
set(_GetWindowsProgramFilesDirIncluded 1)

function(get_windows_program_files_dir var)
    if(NOT WIN32)
        return()
    endif()
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(program_files "Program Files")
    else()
        if(ENV{PROCESSOR_ARCHITECTURE} MATCHES 64 OR ENV{PROCESSOR_ARCHITEW6432} MATCHES 64)
            # 32bit target on 64bit Windows
            set(program_files "Program Files (x86)")
        else()
            # 32bit target on 32bit Windows
            set(program_files "Program Files")
        endif()
    endif()
    if(DEFINED ENV{SystemDrive})
        set(program_files "$ENV{SystemDrive}/${program_files}")
    else()
        set(program_files "C:/${program_files}")
    endif()
    set("${var}" "${program_files}" PARENT_SCOPE)
endfunction()
